# Generated by Django 3.2 on 2024-05-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20240520_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='owner',
        ),
    ]
